<a href="https://colab.research.google.com/github/ajaism/ALma-/blob/master/NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [ ]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [ ]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [ ]:
# Your code here
third_col = random_integers[:5, 2]  # Select first 5 rows of third column
fourth_col = random_integers[:5, 3]  # Select first 5 rows of fourth column

mean = (np.mean(third_col) + np.mean(fourth_col)) / 2  # Calculate the average of the two column means
print(mean)




286058.5


#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [ ]:
# Create the 10 points
import numpy as np
np.random.seed(21)

# Create 2-D array of 10 points with random integral values between 5 and 20 for x-coordinates and y-coordinates
points = np.random.randint(5, 20, size=(10, 2))



print("Points:\n", points)

# print("Manhattan distances:\n", manhattan_dist)


Points:
 [[14 13]
 [ 9  5]
 [ 5 13]
 [ 8 17]
 [ 7  6]
 [15 13]
 [19 17]
 [18 18]
 [14 18]
 [11 15]]


In [ ]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair

# Calculate Euclidean distance for each pair of points
euclidean_dist = []
for i in range(len(points)):
    for j in range(i+1, len(points)):
        dist = np.sqrt((points[i][0]-points[j][0])**2 + (points[i][1]-points[j][1])**2)
        euclidean_dist.append(dist)
print("Euclidean distances:\n", euclidean_dist)



Euclidean distances:
 [9.433981132056603, 9.0, 7.211102550927978, 9.899494936611665, 1.0, 6.4031242374328485, 6.4031242374328485, 5.0, 3.605551275463989, 8.94427190999916, 12.041594578792296, 2.23606797749979, 10.0, 15.620499351813308, 15.811388300841896, 13.92838827718412, 10.198039027185569, 5.0, 7.280109889280518, 10.0, 14.560219778561036, 13.92838827718412, 10.295630140987, 6.324555320336759, 11.045361017187261, 8.06225774829855, 11.0, 10.04987562112089, 6.082762530298219, 3.605551275463989, 10.63014581273465, 16.278820596099706, 16.278820596099706, 13.892443989449804, 9.848857801796104, 5.656854249492381, 5.830951894845301, 5.0990195135927845, 4.47213595499958, 1.4142135623730951, 5.0990195135927845, 8.246211251235321, 4.0, 7.615773105863909, 4.242640687119285]


In [ ]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.

# Calculate Manhattan distance for each pair of points
manhattan_dist = []
for i in range(len(points)):
    for j in range(i+1, len(points)):
        dist = abs(points[i][0]-points[j][0]) + abs(points[i][1]-points[j][1])
        manhattan_dist.append(dist)
print("manhattan distances:\n", manhattan_dist)




manhattan distances:
 [13, 9, 10, 14, 1, 9, 9, 5, 5, 12, 13, 3, 14, 22, 22, 18, 12, 7, 9, 10, 18, 18, 14, 8, 12, 11, 11, 11, 7, 5, 15, 23, 23, 19, 13, 8, 8, 6, 6, 2, 6, 10, 4, 10, 6]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here


import numpy as np

# Create 2-D array of 10 points
np.random.seed(42)
points = np.random.randint(5, 20, size=(10, 2))

# Initialize variables to keep track of closest pairs
min_euclidean_dist = float('inf')
min_manhattan_dist = float('inf')
closest_euclidean_pair = None
closest_manhattan_pair = None

# Calculate distances between each pair of points
for i in range(10):
    for j in range(i+1, 10):
        # Calculate Euclidean distance
        euclidean_dist = np.sqrt(np.sum((points[i] - points[j])**2))
        if euclidean_dist < min_euclidean_dist and euclidean_dist != 0:
            min_euclidean_dist = euclidean_dist
            closest_euclidean_pair = (i, j)
        
        # Calculate Manhattan distance
        manhattan_dist = np.sum(np.abs(points[i] - points[j]))
        if manhattan_dist < min_manhattan_dist and manhattan_dist != 0:
            min_manhattan_dist = manhattan_dist
            closest_manhattan_pair = (i, j)

# Print closest pairs and distances
print("Closest Euclidean distance:", min_euclidean_dist)
print("Closest Euclidean pair:", closest_euclidean_pair)
print("Closest Manhattan distance:", min_manhattan_dist)
print("Closest Manhattan pair:", closest_manhattan_pair)



Closest Euclidean distance: 1.4142135623730951
Closest Euclidean pair: (0, 7)
Closest Manhattan distance: 2
Closest Manhattan pair: (0, 7)


# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [ ]:
# Your code below ..





import numpy as np

# Create a random 10x10 matrix
matrix = np.random.rand(10, 10)

# Initialize an empty list to store the 3x3 blocks
blocks = []

# Loop through the rows of the matrix
for i in range(matrix.shape[0] - 2):
    # Loop through the columns of the matrix
    for j in range(matrix.shape[1] - 2):
        # Extract the 3x3 block
        block = matrix[i:i+3, j:j+3]
        # Append the block to the list
        blocks.append(block)
# matrix
blocks




[array([[0.02058449, 0.96990985, 0.83244264],
        [0.61185289, 0.13949386, 0.29214465],
        [0.60754485, 0.17052412, 0.06505159]]),
 array([[0.96990985, 0.83244264, 0.21233911],
        [0.13949386, 0.29214465, 0.36636184],
        [0.17052412, 0.06505159, 0.94888554]]),
 array([[0.83244264, 0.21233911, 0.18182497],
        [0.29214465, 0.36636184, 0.45606998],
        [0.06505159, 0.94888554, 0.96563203]]),
 array([[0.21233911, 0.18182497, 0.18340451],
        [0.36636184, 0.45606998, 0.78517596],
        [0.94888554, 0.96563203, 0.80839735]]),
 array([[0.18182497, 0.18340451, 0.30424224],
        [0.45606998, 0.78517596, 0.19967378],
        [0.96563203, 0.80839735, 0.30461377]]),
 array([[0.18340451, 0.30424224, 0.52475643],
        [0.78517596, 0.19967378, 0.51423444],
        [0.80839735, 0.30461377, 0.09767211]]),
 array([[0.30424224, 0.52475643, 0.43194502],
        [0.19967378, 0.51423444, 0.59241457],
        [0.30461377, 0.09767211, 0.68423303]]),
 array([[0.52475643,

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [ ]:
# Your function below

import numpy as np

def find_nearest(array, value):
    idx = np.abs(array - value).argmin()
    return array[idx]
    
# Example usage
random_array = np.random.randint(10, 500, size=15)
value = 250
nearest_value = find_nearest(random_array, value)
print(f"Random array: {random_array}")
print(f"Value: {value}")
print(f"Nearest value: {nearest_value}")




Random array: [196 252  95 293  75 179  54  71 450 143 293  37 117  53 349]
Value: 250
Nearest value: 252
